[pytest]
testpaths = tests
pythonpath = .
addopts = -x --timeout=30 --strict-markers -q
filterwarnings =
    ignore::DeprecationWarning:ui.components
    ignore::DeprecationWarning:pkg_resources
    ignore::UserWarning:urllib3
