"""Tests for data.newsapi_feed.

The module wraps the NewsAPI /everything endpoint, normalises article dicts,
deduplicates them by URL, filters by published-at age, and caches results
via CacheManager (JSON sidecar). All network/HTTP is mocked — no real
NewsAPI traffic is generated by these tests.

Branches pinned:

  - SHIPPING_QUERIES configuration
      * Exactly three query specs, each with q/sortBy/language/pageSize keys
      * Every q is a non-empty string

  - _get_api_key / newsapi_available
      * Returns env var when Streamlit secrets absent
      * Returns empty string when nothing configured
      * newsapi_available() reflects bool(_get_api_key())
      * Streamlit secrets access exception is swallowed (falls through to env)

  - _cache_key / _cache_path
      * Stable, date-bearing key format ``newsapi_shipping_<YYYY-MM-DD>``
      * Resulting path nests under ``<cache_dir>/newsapi/`` with .json suffix
      * Slugified filename matches CacheManager._slugify of the key

  - _load_json_cache
      * Missing file → returns None
      * Fresh file → returns the parsed list of dicts
      * Stale file (older than ttl) → returns None
      * Corrupt JSON → returns None and does not raise

  - _save_json_cache
      * Creates the parent directory and writes a valid JSON list
      * datetime values are serialised via default=str (no TypeError)

  - _parse_published_at
      * Z-suffixed ISO string → tz-aware UTC datetime
      * Naive ISO string → assumed UTC
      * Missing / None input → defaults to "now" in UTC
      * Malformed string → defaults to "now" in UTC
      * Non-string (int) → defaults to "now" in UTC

  - _normalise_article
      * Happy path → all fields present, content truncated to 500 chars
      * Empty content falls back to description (also capped at 500)
      * Whitespace-only fields are stripped
      * Title containing "[Removed]" → None
      * Description containing "[Removed]" → None
      * Missing title → None
      * Missing url → None
      * Missing/None source dict → source_name == ""

  - _request_query (requests.get monkeypatched)
      * Network error (RequestException) → []
      * HTTP 401 → []
      * HTTP 500 → []
      * Non-JSON 200 body → []
      * 200 with status != "ok" → []
      * 200 with status "ok" → list of articles from payload
      * 200 with no "articles" key → []
      * HTTP 429 raises _RateLimitError (tenacity wires retry behaviour)

  - fetch_newsapi_articles  (public API; all HTTP mocked, tmp_path cache)
      * Missing API key → returns []
      * Cache hit → reads cached JSON, no HTTP issued, respects max_articles
      * Cache miss → invokes the HTTP layer once per query and writes cache
      * Articles are deduplicated by URL across queries
      * Articles older than ``from_days_back`` are filtered out
      * Result is sorted newest-first
      * ``max_articles`` caps the final list size
      * Empty fetch returns [] and does not write a cache file
      * [Removed] articles are filtered out end-to-end
"""
from __future__ import annotations

import json
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path

import pytest

from data import newsapi_feed as nf
from data.cache_manager import CacheManager


# ─── Helpers ────────────────────────────────────────────────────────────────


class _FakeResponse:
    """Minimal stand-in for requests.Response."""

    def __init__(self, status_code: int = 200, payload=None, raise_json: bool = False):
        self.status_code = status_code
        self._payload = payload if payload is not None else {}
        self._raise_json = raise_json

    def json(self):
        if self._raise_json:
            raise ValueError("not json")
        return self._payload


def _make_article(
    *,
    title: str = "Container rates surge across transpacific",
    url: str = "https://example.com/a1",
    description: str = "Spot rates climbed sharply this week.",
    content: str = "Some article body.",
    author: str = "Jane Doe",
    source: str = "Reuters",
    published_at: str = "2026-05-20T12:00:00Z",
) -> dict:
    """Build a raw NewsAPI-shaped article dict."""
    return {
        "title":       title,
        "url":         url,
        "description": description,
        "content":     content,
        "author":      author,
        "source":      {"name": source} if source is not None else None,
        "publishedAt": published_at,
    }


def _ok_payload(articles: list[dict]) -> dict:
    return {"status": "ok", "totalResults": len(articles), "articles": articles}


def _set_api_key(monkeypatch, value: str = "TEST_KEY_DUMMY") -> None:
    """Ensure _get_api_key() returns ``value`` — bypasses Streamlit secrets."""
    monkeypatch.setattr(nf, "_get_api_key", lambda: value, raising=True)


# ─── SHIPPING_QUERIES configuration ─────────────────────────────────────────


def test_shipping_queries_has_three_specs():
    assert isinstance(nf.SHIPPING_QUERIES, list)
    assert len(nf.SHIPPING_QUERIES) == 3
    for spec in nf.SHIPPING_QUERIES:
        assert {"q", "sortBy", "language", "pageSize"} <= set(spec.keys())
        assert isinstance(spec["q"], str) and spec["q"].strip()
        assert isinstance(spec["pageSize"], int) and spec["pageSize"] > 0
        assert spec["language"] == "en"


# ─── _get_api_key / newsapi_available ───────────────────────────────────────


def test_get_api_key_uses_env_when_secrets_missing(monkeypatch):
    """Streamlit secrets unavailable → falls back to env var."""
    # Force the secrets path to raise so the except branch runs.
    class _BoomSecrets:
        def get(self, *a, **kw):
            raise RuntimeError("no secrets file")
    monkeypatch.setattr(nf.st, "secrets", _BoomSecrets(), raising=False)
    monkeypatch.setenv("NEWS_API_KEY", "ENV_KEY_42")
    assert nf._get_api_key() == "ENV_KEY_42"


def test_get_api_key_returns_empty_when_nothing_configured(monkeypatch):
    class _BoomSecrets:
        def get(self, *a, **kw):
            raise RuntimeError("no secrets file")
    monkeypatch.setattr(nf.st, "secrets", _BoomSecrets(), raising=False)
    monkeypatch.delenv("NEWS_API_KEY", raising=False)
    assert nf._get_api_key() == ""


def test_newsapi_available_reflects_key(monkeypatch):
    monkeypatch.setattr(nf, "_get_api_key", lambda: "abc")
    assert nf.newsapi_available() is True
    monkeypatch.setattr(nf, "_get_api_key", lambda: "")
    assert nf.newsapi_available() is False


# ─── _cache_key / _cache_path ───────────────────────────────────────────────


def test_cache_key_format():
    assert nf._cache_key("2026-05-21") == "newsapi_shipping_2026-05-21"


def test_cache_path_is_under_newsapi_subdir_with_json_suffix(tmp_path):
    cache = CacheManager(tmp_path)
    p = nf._cache_path(cache, "2026-05-21")
    assert isinstance(p, Path)
    assert p.parent == tmp_path / "newsapi"
    assert p.suffix == ".json"
    # Slug should match the cache_manager slugifier applied to the key.
    expected_slug = CacheManager._slugify("newsapi_shipping_2026-05-21")
    assert p.stem == expected_slug


# ─── _load_json_cache ───────────────────────────────────────────────────────


def test_load_json_cache_missing_file(tmp_path):
    assert nf._load_json_cache(tmp_path / "nope.json", ttl_hours=1.0) is None


def test_load_json_cache_fresh_returns_payload(tmp_path):
    p = tmp_path / "news.json"
    payload = [{"title": "x", "url": "u"}]
    p.write_text(json.dumps(payload), encoding="utf-8")
    out = nf._load_json_cache(p, ttl_hours=24.0)
    assert out == payload


def test_load_json_cache_stale_returns_none(tmp_path):
    p = tmp_path / "news.json"
    p.write_text(json.dumps([{"title": "x"}]), encoding="utf-8")
    # Backdate mtime 10 hours.
    old = time.time() - 10 * 3600
    import os
    os.utime(p, (old, old))
    assert nf._load_json_cache(p, ttl_hours=2.0) is None


def test_load_json_cache_corrupt_returns_none(tmp_path):
    p = tmp_path / "news.json"
    p.write_text("{not valid json", encoding="utf-8")
    assert nf._load_json_cache(p, ttl_hours=24.0) is None


# ─── _save_json_cache ───────────────────────────────────────────────────────


def test_save_json_cache_creates_parent_and_writes_list(tmp_path):
    p = tmp_path / "newsapi" / "x.json"
    articles = [{"title": "t", "url": "u"}]
    nf._save_json_cache(p, articles)
    assert p.exists()
    assert json.loads(p.read_text(encoding="utf-8")) == articles


def test_save_json_cache_handles_datetime_via_default_str(tmp_path):
    """published_at is a datetime in normalised dicts — must serialise."""
    p = tmp_path / "newsapi" / "x.json"
    dt = datetime(2026, 5, 20, 12, 0, tzinfo=timezone.utc)
    articles = [{"title": "t", "url": "u", "published_at": dt}]
    nf._save_json_cache(p, articles)  # must not raise
    loaded = json.loads(p.read_text(encoding="utf-8"))
    assert isinstance(loaded[0]["published_at"], str)
    assert "2026-05-20" in loaded[0]["published_at"]


# ─── _parse_published_at ────────────────────────────────────────────────────


def test_parse_published_at_z_suffix():
    dt = nf._parse_published_at("2026-05-20T12:00:00Z")
    assert dt.tzinfo is not None
    assert dt.year == 2026 and dt.month == 5 and dt.day == 20


def test_parse_published_at_naive_string_assumed_utc():
    dt = nf._parse_published_at("2026-05-20T12:00:00")
    assert dt.tzinfo == timezone.utc


def test_parse_published_at_none_defaults_to_now():
    before = datetime.now(tz=timezone.utc)
    dt = nf._parse_published_at(None)
    after = datetime.now(tz=timezone.utc)
    assert before <= dt <= after
    assert dt.tzinfo is not None


def test_parse_published_at_malformed_defaults_to_now():
    before = datetime.now(tz=timezone.utc)
    dt = nf._parse_published_at("definitely not a date")
    after = datetime.now(tz=timezone.utc)
    assert before <= dt <= after


def test_parse_published_at_non_string_defaults_to_now():
    dt = nf._parse_published_at(12345)  # type: ignore[arg-type]
    assert dt.tzinfo is not None


# ─── _normalise_article ─────────────────────────────────────────────────────


def test_normalise_article_happy_path():
    raw = _make_article()
    out = nf._normalise_article(raw)
    assert out is not None
    assert out["title"] == "Container rates surge across transpacific"
    assert out["url"]   == "https://example.com/a1"
    assert out["description"]
    assert out["source_name"] == "Reuters"
    assert out["author"] == "Jane Doe"
    assert isinstance(out["published_at"], datetime)
    assert out["published_at"].tzinfo is not None
    # content is truncated to 500 chars (here it's short, so equal).
    assert out["content"] == "Some article body."


def test_normalise_article_content_truncated_to_500():
    raw = _make_article(content="x" * 1000)
    out = nf._normalise_article(raw)
    assert out is not None
    assert len(out["content"]) == 500
    assert out["content"] == "x" * 500


def test_normalise_article_empty_content_falls_back_to_description():
    raw = _make_article(content="", description="y" * 800)
    out = nf._normalise_article(raw)
    assert out is not None
    assert len(out["content"]) == 500
    assert out["content"] == "y" * 500


def test_normalise_article_strips_whitespace():
    raw = _make_article(title="  title  ", url="  https://e.com/x  ")
    out = nf._normalise_article(raw)
    assert out is not None
    assert out["title"] == "title"
    assert out["url"]   == "https://e.com/x"


def test_normalise_article_removed_in_title_filtered():
    raw = _make_article(title="[Removed]")
    assert nf._normalise_article(raw) is None


def test_normalise_article_removed_in_description_filtered():
    raw = _make_article(description="[Removed]")
    assert nf._normalise_article(raw) is None


def test_normalise_article_missing_title_filtered():
    raw = _make_article(title="")
    assert nf._normalise_article(raw) is None


def test_normalise_article_missing_url_filtered():
    raw = _make_article(url="")
    assert nf._normalise_article(raw) is None


def test_normalise_article_missing_source_dict_yields_empty_source_name():
    raw = _make_article(source=None)
    out = nf._normalise_article(raw)
    assert out is not None
    assert out["source_name"] == ""


# ─── _request_query ─────────────────────────────────────────────────────────


def test_request_query_network_error_returns_empty(monkeypatch):
    import requests as _rq

    def _boom(*a, **kw):
        raise _rq.RequestException("network down")
    monkeypatch.setattr(nf.requests, "get", _boom)

    assert nf._request_query({"q": "x"}, "key") == []


def test_request_query_401_returns_empty(monkeypatch):
    monkeypatch.setattr(nf.requests, "get",
                        lambda *a, **kw: _FakeResponse(status_code=401))
    assert nf._request_query({"q": "x"}, "key") == []


def test_request_query_500_returns_empty(monkeypatch):
    monkeypatch.setattr(nf.requests, "get",
                        lambda *a, **kw: _FakeResponse(status_code=500))
    assert nf._request_query({"q": "x"}, "key") == []


def test_request_query_non_json_returns_empty(monkeypatch):
    monkeypatch.setattr(nf.requests, "get",
                        lambda *a, **kw: _FakeResponse(status_code=200,
                                                       raise_json=True))
    assert nf._request_query({"q": "x"}, "key") == []


def test_request_query_status_not_ok_returns_empty(monkeypatch):
    monkeypatch.setattr(
        nf.requests, "get",
        lambda *a, **kw: _FakeResponse(
            status_code=200,
            payload={"status": "error", "message": "bad"},
        ),
    )
    assert nf._request_query({"q": "x"}, "key") == []


def test_request_query_happy_returns_articles(monkeypatch):
    articles = [_make_article(url=f"https://e.com/{i}") for i in range(3)]
    monkeypatch.setattr(
        nf.requests, "get",
        lambda *a, **kw: _FakeResponse(status_code=200,
                                       payload=_ok_payload(articles)),
    )
    out = nf._request_query({"q": "x"}, "key")
    assert isinstance(out, list)
    assert len(out) == 3
    assert out[0]["url"] == "https://e.com/0"


def test_request_query_ok_but_no_articles_key(monkeypatch):
    monkeypatch.setattr(
        nf.requests, "get",
        lambda *a, **kw: _FakeResponse(status_code=200,
                                       payload={"status": "ok"}),
    )
    assert nf._request_query({"q": "x"}, "key") == []


def test_request_query_429_raises_rate_limit_error(monkeypatch):
    """Tenacity wraps this with retry; with reraise=True the final raise propagates."""
    monkeypatch.setattr(nf.requests, "get",
                        lambda *a, **kw: _FakeResponse(status_code=429))
    # Disable tenacity backoff sleep so the test stays fast.
    monkeypatch.setattr(nf.time, "sleep", lambda *_a, **_kw: None)
    with pytest.raises(nf._RateLimitError):
        nf._request_query({"q": "x"}, "key")


# ─── fetch_newsapi_articles: missing key ────────────────────────────────────


def test_fetch_returns_empty_when_no_api_key(monkeypatch, tmp_path):
    _set_api_key(monkeypatch, "")
    out = nf.fetch_newsapi_articles(cache=CacheManager(tmp_path))
    assert out == []


# ─── fetch_newsapi_articles: cache hit ──────────────────────────────────────


def test_fetch_returns_cached_payload_on_hit(monkeypatch, tmp_path):
    _set_api_key(monkeypatch)
    cache = CacheManager(tmp_path)

    # Seed the cache file for today's date.
    date_str = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    cached = [{"title": f"cached-{i}", "url": f"u{i}"} for i in range(5)]
    path = nf._cache_path(cache, date_str)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(cached), encoding="utf-8")

    # If HTTP is hit, the test should fail.
    def _no_http(*a, **kw):
        raise AssertionError("cache hit should not invoke requests.get")
    monkeypatch.setattr(nf.requests, "get", _no_http)

    out = nf.fetch_newsapi_articles(cache=cache, max_articles=3,
                                    cache_ttl_hours=24.0)
    assert out == cached[:3]


# ─── fetch_newsapi_articles: cache miss + dedup + sort + cap + write ────────


def test_fetch_miss_dedupes_sorts_caps_and_writes_cache(monkeypatch, tmp_path):
    _set_api_key(monkeypatch)
    cache = CacheManager(tmp_path)
    # Don't actually sleep between queries.
    monkeypatch.setattr(nf.time, "sleep", lambda *_a, **_kw: None)

    now = datetime.now(tz=timezone.utc)

    # Build three batches of articles. Overlap URL "dup" across queries to
    # exercise dedup. Vary published_at to exercise sort.
    def _at(offset_hours: int) -> str:
        return (now - timedelta(hours=offset_hours)) \
            .strftime("%Y-%m-%dT%H:%M:%SZ")

    batch1 = [
        _make_article(url="https://e.com/a", published_at=_at(1)),
        _make_article(url="https://e.com/b", published_at=_at(48)),
        _make_article(url="https://e.com/dup", published_at=_at(2)),
    ]
    batch2 = [
        _make_article(url="https://e.com/dup", published_at=_at(2)),   # dup
        _make_article(url="https://e.com/c",   published_at=_at(72)),
    ]
    batch3 = [
        _make_article(url="https://e.com/d", published_at=_at(5)),
        _make_article(title="[Removed]", url="https://e.com/junk",
                      published_at=_at(1)),                            # filtered
    ]
    batches = [batch1, batch2, batch3]
    call_state = {"calls": 0}

    def _fake_get(*a, **kw):
        i = call_state["calls"]
        call_state["calls"] += 1
        return _FakeResponse(status_code=200, payload=_ok_payload(batches[i]))

    monkeypatch.setattr(nf.requests, "get", _fake_get)

    out = nf.fetch_newsapi_articles(
        cache=cache,
        max_articles=10,
        cache_ttl_hours=2.0,
        from_days_back=7,
    )

    # Three HTTP queries fired (one per SHIPPING_QUERIES entry).
    assert call_state["calls"] == 3

    # 5 unique articles: a, b, dup, c, d. The [Removed] one is filtered.
    urls = [a["url"] for a in out]
    assert urls.count("https://e.com/dup") == 1
    assert set(urls) == {
        "https://e.com/a", "https://e.com/b", "https://e.com/dup",
        "https://e.com/c", "https://e.com/d",
    }

    # Newest first.
    times = [a["published_at"] for a in out]
    assert times == sorted(times, reverse=True)

    # Cache file written.
    date_str = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    cache_file = nf._cache_path(cache, date_str)
    assert cache_file.exists()
    loaded = json.loads(cache_file.read_text(encoding="utf-8"))
    assert len(loaded) == len(out)


def test_fetch_filters_articles_older_than_window(monkeypatch, tmp_path):
    _set_api_key(monkeypatch)
    cache = CacheManager(tmp_path)
    monkeypatch.setattr(nf.time, "sleep", lambda *_a, **_kw: None)

    now = datetime.now(tz=timezone.utc)
    fresh = (now - timedelta(days=1)).strftime("%Y-%m-%dT%H:%M:%SZ")
    stale = (now - timedelta(days=20)).strftime("%Y-%m-%dT%H:%M:%SZ")

    articles = [
        _make_article(url="https://e.com/fresh", published_at=fresh),
        _make_article(url="https://e.com/stale", published_at=stale),
    ]

    monkeypatch.setattr(
        nf.requests, "get",
        lambda *a, **kw: _FakeResponse(status_code=200,
                                       payload=_ok_payload(articles)),
    )

    out = nf.fetch_newsapi_articles(
        cache=cache,
        max_articles=10,
        cache_ttl_hours=2.0,
        from_days_back=7,
    )
    urls = [a["url"] for a in out]
    assert "https://e.com/fresh" in urls
    assert "https://e.com/stale" not in urls


def test_fetch_max_articles_caps_result(monkeypatch, tmp_path):
    _set_api_key(monkeypatch)
    cache = CacheManager(tmp_path)
    monkeypatch.setattr(nf.time, "sleep", lambda *_a, **_kw: None)

    now = datetime.now(tz=timezone.utc)
    articles = [
        _make_article(
            url=f"https://e.com/x{i}",
            published_at=(now - timedelta(hours=i)).strftime("%Y-%m-%dT%H:%M:%SZ"),
        )
        for i in range(8)
    ]
    monkeypatch.setattr(
        nf.requests, "get",
        lambda *a, **kw: _FakeResponse(status_code=200,
                                       payload=_ok_payload(articles)),
    )

    out = nf.fetch_newsapi_articles(
        cache=cache,
        max_articles=3,
        cache_ttl_hours=2.0,
        from_days_back=7,
    )
    assert len(out) == 3


def test_fetch_empty_does_not_write_cache(monkeypatch, tmp_path):
    """All three queries return empty → no cache file persisted."""
    _set_api_key(monkeypatch)
    cache = CacheManager(tmp_path)
    monkeypatch.setattr(nf.time, "sleep", lambda *_a, **_kw: None)

    monkeypatch.setattr(
        nf.requests, "get",
        lambda *a, **kw: _FakeResponse(status_code=200,
                                       payload=_ok_payload([])),
    )

    out = nf.fetch_newsapi_articles(cache=cache, cache_ttl_hours=2.0)
    assert out == []

    date_str = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    cache_file = nf._cache_path(cache, date_str)
    assert not cache_file.exists()
