"""Tests for utils.view_export — per-tab PDF export.

We don't compare pixel output. We pin:
  - Snapshot dataclasses construct cleanly
  - build_view_pdf returns non-empty bytes that look like PDF
  - The PDF embeds the title / headline / section text in extractable form
    (PDF byte sequence contains those strings, after the latin-1 sanitizer)
  - The _utf8_safe sanitizer handles every UTF-8 character we care about
  - Empty / minimal snapshots don't crash
"""
from __future__ import annotations

import pytest

from utils.view_export import (
    ViewSection,
    ViewSnapshot,
    ViewTable,
    _utf8_safe,
    build_view_pdf,
)


# ─── _utf8_safe sanitizer ──────────────────────────────────────────────────

def test_utf8_safe_empty_and_none() -> None:
    assert _utf8_safe("") == ""
    assert _utf8_safe(None) == ""


def test_utf8_safe_replaces_common_unicode() -> None:
    out = _utf8_safe("Asia—Europe rate (+18%) → ZIM ‘bullish’ · Δr ≤ 0.20")
    # Should encode cleanly to latin-1 now.
    out.encode("latin-1")
    # And the substitutions we promised should be in place.
    assert "Asia--Europe" in out
    assert "->" in out
    assert "<=" in out
    assert "'bullish'" in out
    assert "D" in out  # Delta replacement
    assert "*" in out  # middle-dot replacement


def test_utf8_safe_passes_through_plain_latin1() -> None:
    assert _utf8_safe("plain ASCII text") == "plain ASCII text"
    assert _utf8_safe("Café") == "Café"  # latin-1 representable


def test_utf8_safe_drops_truly_unknown_codepoints() -> None:
    """Anything we don't have a replacement for AND that's not latin-1 gets
    replaced with '?' rather than crashing the PDF."""
    out = _utf8_safe("🚢 emoji should fall back")
    # Just verify it's now latin-1 safe.
    out.encode("latin-1")


# ─── ViewSnapshot construction ─────────────────────────────────────────────

def test_snapshot_minimal() -> None:
    snap = ViewSnapshot(title="Test View")
    assert snap.title == "Test View"
    assert snap.sections == []
    assert snap.body == ""


def test_view_table_empty_is_valid() -> None:
    t = ViewTable(title="Empty", headers=[])
    assert t.rows == []


def test_view_section_with_all_fields() -> None:
    section = ViewSection(
        title="Section A",
        body="Some prose.",
        bullets=["b1", "b2"],
        tables=[ViewTable(title="T", headers=["A", "B"], rows=[["1", "2"]])],
    )
    assert section.title == "Section A"
    assert len(section.bullets) == 2
    assert len(section.tables) == 1
    assert section.tables[0].rows[0] == ["1", "2"]


# ─── build_view_pdf — output shape ─────────────────────────────────────────

def test_build_pdf_returns_non_empty_bytes() -> None:
    snap = ViewSnapshot(title="Daily Briefing", subtitle="Test export")
    out = build_view_pdf(snap)
    assert isinstance(out, bytes)
    assert len(out) > 500  # any non-empty PDF is at least a few hundred bytes
    assert out[:4] == b"%PDF"  # PDF magic number


def test_build_pdf_with_full_content() -> None:
    snap = ViewSnapshot(
        title="Daily Briefing",
        subtitle="Shipping signals for 2026-05-20",
        headline="Shipping Stress Index at 0.62 (Elevated)",
        body=(
            "Fleet-wide stress moved up 4pp week-over-week as chokepoint "
            "disruption widened.\n\n"
            "Top equity ideas concentrate in ZIM and MATX."
        ),
        sections=[
            ViewSection(
                title="SSI Breakdown",
                bullets=[
                    "chokepoint: 0.71",
                    "congestion: 0.55",
                    "weather: 0.42",
                ],
            ),
            ViewSection(
                title="Route Forecasts",
                tables=[ViewTable(
                    title="Top 3 by 30d stress",
                    headers=["Route", "Current", "30d", "Trend"],
                    rows=[
                        ["transpacific_eb", "0.55", "0.62", "Worsening"],
                        ["asia_europe",     "0.71", "0.68", "Improving"],
                        ["middle_east_eu",  "0.53", "0.53", "Stable"],
                    ],
                )],
            ),
        ],
        footer_note="Generated by Ship Tracker view_export",
    )
    out = build_view_pdf(snap)
    assert out[:4] == b"%PDF"
    # A full-content snapshot should produce more than a stub PDF.
    # FPDF compresses text streams so we don't search for substrings; size +
    # the PDF magic number are the practical fidelity checks here.
    assert len(out) > 1500
    # PDF metadata holds the title field uncompressed (we set it via
    # pdf.set_title at the top of build_view_pdf).
    assert b"Daily Briefing" in out


def test_build_pdf_handles_unicode_throughout() -> None:
    """Headline + body + section bullets + table cells with smart quotes,
    arrows, em-dashes — every field gets sanitized."""
    snap = ViewSnapshot(
        title="Convergence Lab — Asia↔Europe",
        subtitle="r ≥ 0.30 over the trailing 90 days",
        headline="Top pair: rate:asia_europe ↔ macro:BDI · Δr +0.41",
        body="The pair’s correlation strengthened from “0.32” to “0.73”.",
        sections=[
            ViewSection(
                title="Decoupling Watch",
                bullets=["ZIM ↔ DAC: −0.40 → +0.55"],
                tables=[ViewTable(
                    title="Top 2",
                    headers=["Pair", "Δr"],
                    rows=[["A ↔ B", "+0.45"], ["C ↔ D", "−0.30"]],
                )],
            ),
        ],
    )
    out = build_view_pdf(snap)
    assert out[:4] == b"%PDF"
    assert len(out) > 800


def test_build_pdf_empty_sections() -> None:
    """Empty sections shouldn't crash."""
    snap = ViewSnapshot(
        title="Empty View",
        sections=[ViewSection(title="Nothing here")],
    )
    out = build_view_pdf(snap)
    assert out[:4] == b"%PDF"


def test_build_pdf_only_title() -> None:
    """Bare-minimum snapshot."""
    out = build_view_pdf(ViewSnapshot(title="X"))
    assert out[:4] == b"%PDF"


def test_build_pdf_with_long_body_paginates_safely() -> None:
    """A snapshot longer than one page must not raise."""
    long_para = "Lorem ipsum dolor sit amet. " * 80
    body = "\n\n".join([long_para] * 6)
    sections = [
        ViewSection(title=f"Section {i}", body=long_para)
        for i in range(6)
    ]
    out = build_view_pdf(ViewSnapshot(
        title="Long View",
        body=body,
        sections=sections,
    ))
    assert out[:4] == b"%PDF"
    # A multi-page PDF will be substantially larger.
    assert len(out) > 3_000
