"""Mandatory not-advice disclosure on every downloadable export artifact.

R005 disclosed the PDF/HTML reports; the markdown + Excel artifacts that travel
OUTSIDE the app (Slack/Notion/email/a shared workbook) shipped modeled signals
and synthetic series with no disclosure at all. These tests pin the gate
(utils.disclosure.assert_disclosed) and ratchet the disclosure into the two
human-facing export formats so a future edit can't silently drop it.
"""
from __future__ import annotations

import io

import pytest

from utils.disclosure import (
    MODELED_NOTICE,
    DisclosureError,
    assert_disclosed,
    is_disclosed,
)


# ── The gate itself ─────────────────────────────────────────────────────────

def test_modeled_notice_carries_the_canonical_marker() -> None:
    assert "not investment advice" in MODELED_NOTICE.lower()


def test_is_disclosed_accepts_both_marker_phrasings() -> None:
    assert is_disclosed("... this is not investment advice ...")
    # The canonical investor-report disclaimer phrasing also passes the gate.
    assert is_disclosed("It does not constitute investment advice.")
    assert not is_disclosed("Generated by the platform.")
    assert not is_disclosed("")


def test_assert_disclosed_raises_without_a_marker() -> None:
    with pytest.raises(DisclosureError):
        assert_disclosed("Generated by ShipTracker Intelligence Platform")
    with pytest.raises(DisclosureError):
        assert_disclosed("")


def test_assert_disclosed_passes_with_the_notice() -> None:
    assert_disclosed(f"some report body\n{MODELED_NOTICE}")   # no raise


# ── Markdown export ratchet ─────────────────────────────────────────────────

def test_markdown_export_carries_disclosure() -> None:
    from utils.markdown_export import report_to_markdown

    md = report_to_markdown({})          # degrades gracefully on an empty payload
    assert "not investment advice" in md.lower()
    # The renderer's own gate must have been satisfied (no raise above) — and
    # re-asserting documents the invariant at the call site.
    assert_disclosed(md)


# ── Excel export ratchet ────────────────────────────────────────────────────

def _xlsx_text(xlsx_bytes: bytes) -> str:
    """Flatten every cell value across every sheet to one lower-cased string."""
    from openpyxl import load_workbook

    wb = load_workbook(io.BytesIO(xlsx_bytes), read_only=True, data_only=True)
    chunks: list[str] = []
    for ws in wb.worksheets:
        for row in ws.iter_rows(values_only=True):
            for cell in row:
                if cell is not None:
                    chunks.append(str(cell))
    return " ".join(chunks).lower()


def test_excel_full_report_carries_disclosure() -> None:
    from utils.excel_export import export_to_excel

    data = {
        "signals": [{"ticker": "ZIM", "direction": "Bullish", "conviction": 0.8}],
        "freight_rates": [],
    }
    text = _xlsx_text(export_to_excel(data, report_type="full"))
    assert "not investment advice" in text


def test_excel_signal_export_carries_disclosure() -> None:
    from utils.excel_export import export_signal_data

    text = _xlsx_text(export_signal_data(
        [{"ticker": "ZIM", "direction": "Bullish", "conviction_score": 0.7}]))
    assert "not investment advice" in text
