"""
utils/excel_export.py
──────────────────────
Multi-sheet Excel export for the ShipTracker Intelligence Platform.

Produces institutional-quality workbooks with:
  - Navy header rows (RGB 15, 40, 90 text on white background, bold)
  - Alternating white / light-gray data rows
  - Auto-fit column widths (approximated via openpyxl)
  - Frozen top row per sheet
  - Platform footer on every sheet

Dependencies: openpyxl
"""
from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any

from loguru import logger

try:
    import openpyxl
    from openpyxl import Workbook
    from openpyxl.styles import (
        Alignment,
        Border,
        Font,
        PatternFill,
        Side,
    )
    from openpyxl.utils import get_column_letter
    _OPENPYXL_OK = True
except ImportError:
    _OPENPYXL_OK = False
    logger.error("openpyxl not installed — Excel export unavailable")


# ── Palette ────────────────────────────────────────────────────────────────────

_NAVY           = "0F285A"      # RGB 15, 40, 90 — header text colour
_HEADER_BG      = "0F285A"      # deep navy header background
_WHITE          = "FFFFFF"
_ALT_ROW_BG     = "F0F2F6"      # soft grey alternating row
_GREEN_TEXT     = "0A6B3C"
_RED_TEXT       = "B91C1C"
_FOOTER_GREY    = "8A8A8A"

PLATFORM_FOOTER = "Generated by ShipTracker Intelligence Platform"

# Pre-built style objects (module-level singletons for performance)
_HEADER_FONT    = Font(name="Calibri", bold=True,  color=_WHITE, size=10)
_DATA_FONT      = Font(name="Calibri", bold=False, color=_NAVY,  size=10)
_TITLE_FONT     = Font(name="Calibri", bold=True,  color=_NAVY,  size=13)
_FOOTER_FONT    = Font(name="Calibri", italic=True, color=_FOOTER_GREY, size=9)

_FILL_HEADER    = PatternFill(fill_type="solid", fgColor=_HEADER_BG)
_FILL_WHITE     = PatternFill(fill_type="solid", fgColor=_WHITE)
_FILL_ALT       = PatternFill(fill_type="solid", fgColor=_ALT_ROW_BG)

_THIN_SIDE      = Side(style="thin", color="D1D5DB")
_THIN_BORDER    = Border(
    left=_THIN_SIDE, right=_THIN_SIDE,
    top=_THIN_SIDE, bottom=_THIN_SIDE,
)

_ALIGN_LEFT     = Alignment(horizontal="left",   vertical="center", wrap_text=False)
_ALIGN_CENTER   = Alignment(horizontal="center", vertical="center", wrap_text=False)
_ALIGN_RIGHT    = Alignment(horizontal="right",  vertical="center", wrap_text=False)


# ── Private style helpers ─────────────────────────────────────────────────────

def _require_openpyxl() -> None:
    if not _OPENPYXL_OK:
        raise ImportError(
            "openpyxl is required for Excel export. "
            "Install it with: pip install openpyxl"
        )


def _style_header_row(ws, row_num: int) -> None:
    """Navy background, white bold text on a header row."""
    for cell in ws[row_num]:
        cell.fill      = _FILL_HEADER
        cell.font      = _HEADER_FONT
        cell.alignment = _ALIGN_CENTER
        cell.border    = _THIN_BORDER


def _style_data_row(ws, row_num: int, alt: bool = False) -> None:
    """Alternating fill + navy data font; right-align numbers with green/red colouring."""
    fill = _FILL_ALT if alt else _FILL_WHITE
    for cell in ws[row_num]:
        cell.fill   = fill
        cell.border = _THIN_BORDER
        if isinstance(cell.value, (int, float)):
            cell.alignment = _ALIGN_RIGHT
            if cell.value > 0:
                cell.font = Font(name="Calibri", size=10, color=_GREEN_TEXT)
            elif cell.value < 0:
                cell.font = Font(name="Calibri", size=10, color=_RED_TEXT)
            else:
                cell.font = _DATA_FONT
        else:
            cell.font      = _DATA_FONT
            cell.alignment = _ALIGN_LEFT


def _auto_fit_columns(ws, min_width: int = 9, max_width: int = 50) -> None:
    """Auto-size column widths from content length (approximation)."""
    for col_cells in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col_cells[0].column)
        for cell in col_cells:
            try:
                val_len = len(str(cell.value)) if cell.value is not None else 0
                if val_len > max_len:
                    max_len = val_len
            except Exception:
                pass
        ws.column_dimensions[col_letter].width = min(max(max_len * 1.1 + 2, min_width), max_width)


def _freeze_top_rows(ws, freeze_row: int = 3) -> None:
    """Freeze rows above freeze_row so header stays visible on scroll."""
    ws.freeze_panes = f"A{freeze_row}"


def _add_sheet_title(ws, title: str, ncols: int = 7) -> None:
    """Write a large styled title in row 1."""
    ws.append([title])
    r = ws.max_row
    ws.row_dimensions[r].height = 22
    cell = ws.cell(row=r, column=1)
    cell.font      = _TITLE_FONT
    cell.alignment = _ALIGN_LEFT
    if ncols > 1:
        try:
            ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=min(ncols, 20))
        except Exception:
            pass


def _write_table(ws, headers: list[str], rows: list[list[Any]]) -> int:
    """Append header row then data rows; returns the row index after the last data row."""
    ws.append(headers)
    _style_header_row(ws, ws.max_row)

    for i, row in enumerate(rows):
        ws.append(row)
        _style_data_row(ws, ws.max_row, alt=(i % 2 == 1))

    return ws.max_row


def _add_footer(ws, row_num: int, ncols: int) -> None:
    """Append platform footer spanning all columns."""
    # Ensure we're writing at exactly row_num by padding if needed
    while ws.max_row < row_num - 1:
        ws.append([])
    ws.append([PLATFORM_FOOTER])
    r = ws.max_row
    ws.row_dimensions[r].height = 14
    cell = ws.cell(row=r, column=1)
    cell.font      = _FOOTER_FONT
    cell.alignment = _ALIGN_LEFT
    if ncols > 1:
        try:
            ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=min(ncols, 20))
        except Exception:
            pass


def _placeholder_row(ws, ncols: int, msg: str = "No data available for this period.") -> None:
    ws.append([msg])
    r = ws.max_row
    cell = ws.cell(row=r, column=1)
    cell.font      = Font(name="Calibri", italic=True, color=_FOOTER_GREY, size=10)
    cell.alignment = _ALIGN_LEFT
    if ncols > 1:
        try:
            ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=min(ncols, 20))
        except Exception:
            pass


def _workbook_to_bytes(wb) -> bytes:
    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf.read()


# ── Sheet builders ────────────────────────────────────────────────────────────

def _build_summary(ws, data: dict) -> None:
    headers = ["Metric", "Value"]
    ncols   = len(headers)
    generated = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    _add_sheet_title(ws, "Market Summary Dashboard", ncols)
    ws.append([])

    # Extract metrics safely
    freight    = data.get("freight_data") or {}
    bdi        = (freight.get("bdi") or freight.get("BDI") or
                  freight.get("baltic_dry_index") or "N/A")

    sentiment  = data.get("sentiment_data") or []
    if isinstance(sentiment, list) and sentiment:
        scores   = [s.get("score", 0) for s in sentiment if isinstance(s, dict)]
        avg_sent = sum(scores) / len(scores) if scores else 0
        top_sent = "Bullish" if avg_sent > 0.1 else ("Bearish" if avg_sent < -0.1 else "Neutral")
    elif isinstance(sentiment, dict):
        top_sent = sentiment.get("overall", "N/A")
    else:
        top_sent = "N/A"

    port_results  = data.get("port_results")  or []
    route_results = data.get("route_results") or []
    insights      = data.get("insights")      or []
    stock_data    = data.get("stock_data")    or []
    macro_data    = data.get("macro_data")    or {}

    signals_count = len(stock_data) if isinstance(stock_data, list) else 0

    rows = [
        ["Report Generated",      generated],
        ["Baltic Dry Index (BDI)", str(bdi)],
        ["Overall Sentiment",      top_sent],
        ["Ports Monitored",        len(port_results)],
        ["Routes Monitored",       len(route_results)],
        ["Market Signals",         signals_count],
        ["Key Insights",           len(insights) if isinstance(insights, list) else "N/A"],
        ["Macro Series Tracked",   len(macro_data) if isinstance(macro_data, dict) else "N/A"],
        ["Data Freshness",         "Real-time / T+1 lag"],
        ["Platform",               "ShipTracker Intelligence v2.1"],
    ]

    last_data_row = _write_table(ws, headers, rows)
    ws.append([])
    _add_footer(ws, last_data_row + 2, ncols)
    _auto_fit_columns(ws)
    _freeze_top_rows(ws, freeze_row=3)


def _build_freight_rates(ws, data: dict) -> None:
    headers = ["Route Name", "Current Rate (USD/TEU)", "WoW Change (%)", "YoY Change (%)", "Trend", "Last Updated"]
    ncols   = len(headers)
    generated = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    _add_sheet_title(ws, "Freight Rate Monitor", ncols)
    ws.append([])

    freight_data = data.get("freight_data") or {}
    routes_raw   = (freight_data.get("routes") or
                    freight_data.get("route_list") or
                    data.get("route_results") or [])

    rows: list[list[Any]] = []
    for i, route in enumerate(routes_raw):
        if isinstance(route, dict):
            rows.append([
                route.get("name") or route.get("route") or route.get("route_name") or f"Route {i+1}",
                route.get("rate") or route.get("current_rate") or route.get("spot_rate") or "N/A",
                route.get("wow_change") or route.get("week_change") or route.get("rate_change_pct") or "N/A",
                route.get("yoy_change") or route.get("year_change") or "N/A",
                route.get("trend") or route.get("signal") or "—",
                route.get("updated") or route.get("timestamp") or generated,
            ])
        else:
            rows.append([str(route), "N/A", "N/A", "N/A", "—", generated])

    if not rows:
        _placeholder_row(ws, ncols)
        last = ws.max_row
    else:
        last = _write_table(ws, headers, rows)

    ws.append([])
    _add_footer(ws, last + 2, ncols)
    _auto_fit_columns(ws)
    _freeze_top_rows(ws, freeze_row=3)


def _build_market_signals(ws, data: dict) -> None:
    headers = ["Ticker", "Signal Type", "Strength", "Confidence (%)", "Price at Signal", "Timestamp", "Notes"]
    ncols   = len(headers)
    generated = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    _add_sheet_title(ws, "Market Signals", ncols)
    ws.append([])

    stock_data = data.get("stock_data") or []
    rows: list[list[Any]] = []

    for i, item in enumerate(stock_data):
        if isinstance(item, dict):
            rows.append([
                item.get("ticker") or item.get("symbol") or "—",
                item.get("signal_type") or item.get("signal") or "—",
                item.get("strength") or "—",
                item.get("confidence") or item.get("confidence_pct") or "—",
                item.get("price") or item.get("price_at_signal") or item.get("last_price") or "—",
                item.get("timestamp") or item.get("date") or generated,
                item.get("notes") or item.get("note") or item.get("summary") or "",
            ])
        else:
            rows.append([str(item)] + ["—"] * (ncols - 1))

    if not rows:
        _placeholder_row(ws, ncols)
        last = ws.max_row
    else:
        last = _write_table(ws, headers, rows)

    ws.append([])
    _add_footer(ws, last + 2, ncols)
    _auto_fit_columns(ws)
    _freeze_top_rows(ws, freeze_row=3)


def _build_port_intelligence(ws, data: dict) -> None:
    headers = ["Port Name", "Congestion Level", "Avg Wait Time (hrs)", "Throughput (TEU/day)", "Region", "Status", "Last Updated"]
    ncols   = len(headers)
    generated = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    _add_sheet_title(ws, "Port Intelligence", ncols)
    ws.append([])

    port_results = data.get("port_results") or []
    rows: list[list[Any]] = []

    for i, port in enumerate(port_results):
        if isinstance(port, dict):
            rows.append([
                port.get("name") or port.get("port") or port.get("port_name") or f"Port {i+1}",
                port.get("congestion") or port.get("congestion_level") or port.get("congestion_score") or "—",
                port.get("wait_time") or port.get("avg_wait_hrs") or port.get("avg_dwell_days") or "—",
                port.get("throughput") or port.get("teu_per_day") or port.get("weekly_calls") or "—",
                port.get("region") or port.get("country") or "—",
                port.get("status") or "Operational",
                port.get("updated") or port.get("timestamp") or generated,
            ])
        else:
            rows.append([str(port)] + ["—"] * (ncols - 1))

    if not rows:
        _placeholder_row(ws, ncols)
        last = ws.max_row
    else:
        last = _write_table(ws, headers, rows)

    ws.append([])
    _add_footer(ws, last + 2, ncols)
    _auto_fit_columns(ws)
    _freeze_top_rows(ws, freeze_row=3)


def _build_macro_indicators(ws, data: dict) -> None:
    headers = ["Indicator", "Current Value", "Prior Value", "Delta", "Delta %", "Direction", "Source"]
    ncols   = len(headers)
    generated = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    _add_sheet_title(ws, "Macro Indicators", ncols)
    ws.append([])

    macro_data = data.get("macro_data") or {}
    if isinstance(macro_data, dict):
        items = [dict(indicator=k, **v) if isinstance(v, dict) else dict(indicator=k, current=v)
                 for k, v in macro_data.items()]
    elif isinstance(macro_data, list):
        items = macro_data
    else:
        items = []

    rows: list[list[Any]] = []
    for item in items:
        if isinstance(item, dict):
            delta = item.get("delta") or item.get("change") or "—"
            try:
                direction = "▲" if float(str(delta).replace(",", "")) > 0 else "▼"
            except (ValueError, TypeError):
                direction = "—"
            rows.append([
                item.get("indicator") or item.get("name") or item.get("series_id") or "—",
                item.get("current") or item.get("value") or item.get("current_value") or "—",
                item.get("prior") or item.get("prior_value") or item.get("previous") or "—",
                delta,
                item.get("delta_pct") or item.get("change_pct") or item.get("pct_change") or "—",
                direction,
                item.get("source") or "—",
            ])
        else:
            rows.append([str(item)] + ["—"] * (ncols - 1))

    if not rows:
        _placeholder_row(ws, ncols)
        last = ws.max_row
    else:
        last = _write_table(ws, headers, rows)

    ws.append([])
    _add_footer(ws, last + 2, ncols)
    _auto_fit_columns(ws)
    _freeze_top_rows(ws, freeze_row=3)


def _build_stock_performance(ws, data: dict) -> None:
    headers = ["Ticker", "Company", "Price (USD)", "Day Change (%)", "YTD (%)", "Market Cap", "Sector", "Exchange"]
    ncols   = len(headers)
    generated = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    _add_sheet_title(ws, "Stock Performance", ncols)
    ws.append([])

    stock_data = data.get("stock_data") or []
    if isinstance(stock_data, dict):
        stock_data = [dict(ticker=k, **v) if isinstance(v, dict) else dict(ticker=k, price=v)
                      for k, v in stock_data.items()]

    rows: list[list[Any]] = []
    for item in stock_data:
        if isinstance(item, dict):
            rows.append([
                item.get("ticker") or item.get("symbol") or "—",
                item.get("company") or item.get("name") or "—",
                item.get("price") or item.get("last_price") or item.get("close") or "—",
                item.get("day_change") or item.get("day_change_pct") or item.get("change_pct") or "—",
                item.get("ytd") or item.get("ytd_pct") or item.get("ytd_return") or "—",
                item.get("market_cap") or item.get("mkt_cap") or "—",
                item.get("sector") or "Shipping",
                item.get("exchange") or "—",
            ])
        else:
            rows.append([str(item)] + ["—"] * (ncols - 1))

    if not rows:
        _placeholder_row(ws, ncols)
        last = ws.max_row
    else:
        last = _write_table(ws, headers, rows)

    ws.append([])
    _add_footer(ws, last + 2, ncols)
    _auto_fit_columns(ws)
    _freeze_top_rows(ws, freeze_row=3)


def _build_news_sentiment(ws, data: dict) -> None:
    headers = ["Headline", "Source", "Sentiment Score", "Sentiment Label", "Topic", "Date", "URL"]
    ncols   = len(headers)
    generated = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    _add_sheet_title(ws, "News Sentiment Analysis", ncols)
    ws.append([])

    sentiment_data = data.get("sentiment_data") or []
    if isinstance(sentiment_data, dict):
        sentiment_data = (sentiment_data.get("articles") or
                          sentiment_data.get("news") or
                          sentiment_data.get("items") or [])

    rows: list[list[Any]] = []
    for item in sentiment_data:
        if isinstance(item, dict):
            raw_score = item.get("score") or item.get("sentiment_score") or item.get("sentiment") or 0
            try:
                score_f = float(raw_score)
                label   = "Bullish" if score_f > 0.15 else ("Bearish" if score_f < -0.15 else "Neutral")
            except (ValueError, TypeError):
                score_f = raw_score
                label   = str(raw_score)
            rows.append([
                (item.get("headline") or item.get("title") or item.get("text") or "—")[:200],
                item.get("source") or item.get("publisher") or "—",
                score_f,
                label,
                item.get("topic") or item.get("category") or "Shipping",
                item.get("date") or item.get("published") or item.get("timestamp") or generated,
                item.get("url") or item.get("link") or "—",
            ])
        else:
            rows.append([str(item)] + ["—"] * (ncols - 1))

    if not rows:
        _placeholder_row(ws, ncols)
        last = ws.max_row
    else:
        last = _write_table(ws, headers, rows)

    ws.append([])
    _add_footer(ws, last + 2, ncols)
    _auto_fit_columns(ws)
    _freeze_top_rows(ws, freeze_row=3)


# ── Sheet registry ────────────────────────────────────────────────────────────

_SHEET_BUILDERS: dict[str, Any] = {
    "Summary":          _build_summary,
    "Freight Rates":    _build_freight_rates,
    "Market Signals":   _build_market_signals,
    "Port Intelligence":_build_port_intelligence,
    "Macro Indicators": _build_macro_indicators,
    "Stock Performance":_build_stock_performance,
    "News Sentiment":   _build_news_sentiment,
}

_SUBSET_MAP: dict[str, list[str]] = {
    "full":      list(_SHEET_BUILDERS.keys()),
    "freight":   ["Summary", "Freight Rates"],
    "port":      ["Summary", "Port Intelligence"],
    "stock":     ["Summary", "Stock Performance", "Market Signals"],
    "macro":     ["Summary", "Macro Indicators"],
    "sentiment": ["Summary", "News Sentiment"],
    "signals":   ["Summary", "Market Signals"],
}


# ── Public API ────────────────────────────────────────────────────────────────

def export_to_excel(data: dict, report_type: str = "full") -> bytes:
    """Build a multi-sheet Excel workbook from platform data and return raw bytes.

    Parameters
    ----------
    data : dict
        May contain any of: port_results, route_results, insights,
        freight_data, macro_data, stock_data, sentiment_data.
    report_type : str
        "full" for all sheets, or a subset key: "freight", "port",
        "stock", "macro", "sentiment", "signals".

    Returns
    -------
    bytes
        Raw .xlsx bytes suitable for st.download_button or file I/O.
    """
    _require_openpyxl()

    if data is None:
        data = {}

    wb = Workbook()
    # Remove the default empty sheet openpyxl creates
    default_sheet = wb.active
    if default_sheet is not None:
        wb.remove(default_sheet)

    include = _SUBSET_MAP.get(report_type, _SUBSET_MAP["full"])

    for sheet_name in include:
        builder = _SHEET_BUILDERS.get(sheet_name)
        if builder is None:
            continue
        ws = wb.create_sheet(title=sheet_name)
        ws.sheet_view.showGridLines = False
        ws.row_dimensions[1].height = 24
        try:
            builder(ws, data)
        except Exception as exc:
            logger.error(f"excel_export: error building sheet '{sheet_name}': {exc}")
            ws.cell(row=3, column=1, value=f"Sheet build error: {exc}")

    if not wb.sheetnames:
        # Safety: never return an empty workbook
        ws = wb.create_sheet("Summary")
        ws.cell(row=1, column=1, value="No data available.")

    return _workbook_to_bytes(wb)


def get_excel_download_button_args(data: dict, report_type: str = "full") -> dict:
    """Prepare arguments for st.download_button to offer an Excel export.

    Usage
    -----
        args = get_excel_download_button_args(data)
        st.download_button(**args)

    Parameters
    ----------
    data : dict
        Platform data dict (same schema as export_to_excel).
    report_type : str
        Workbook subset: "full", "freight", "port", "stock", "macro",
        "sentiment", or "signals".

    Returns
    -------
    dict with keys: label, data, file_name, mime
    """
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y%m%d_%H%M")
    file_name = f"shiptracker_{report_type}_{timestamp}.xlsx"
    excel_bytes = export_to_excel(data, report_type=report_type)
    return {
        "label":     "Download Excel Report",
        "data":      excel_bytes,
        "file_name": file_name,
        "mime":      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    }


# ── Legacy single-sheet helpers (preserved for backward compatibility) ────────

def export_port_data(port_results: list) -> bytes:
    """Export port demand data as a single-sheet Excel workbook."""
    return export_to_excel({"port_results": port_results}, report_type="port")


def export_route_data(route_results: list, freight_data: dict) -> bytes:
    """Export route and freight rate data as a two-sheet Excel workbook."""
    return export_to_excel(
        {"route_results": route_results, "freight_data": freight_data},
        report_type="freight",
    )


def export_signal_data(signals: list) -> bytes:
    """Export alpha signals as a single-sheet Excel workbook."""
    return export_to_excel({"stock_data": signals}, report_type="signals")


def export_full_report(
    port_results,
    route_results,
    insights,
    freight_data,
    macro_data,
    stock_data,
    signals=None,
) -> bytes:
    """Export everything as a styled multi-sheet Excel workbook.

    All parameters map to the corresponding data dict keys consumed by
    export_to_excel().  The ``signals`` argument is merged into stock_data
    when provided.
    """
    effective_stock = signals or stock_data
    return export_to_excel(
        {
            "port_results":   port_results,
            "route_results":  route_results,
            "insights":       insights,
            "freight_data":   freight_data,
            "macro_data":     macro_data,
            "stock_data":     effective_stock,
        },
        report_type="full",
    )
