"""tab_commentary.py — WSJ-style Daily Market Commentary page.

Displays auto-generated editorial narrative about market conditions,
key movers, forward outlook, and index dashboard.

The narrative text is produced by ``processing.market_commentary`` and
``processing.index_tracker`` (forthcoming: ``engine.narration_engine``).
Data shown in this tab is *modeled* — generated deterministically from
live feeds — and is labeled as such via ``live_data_badge``.
"""
from __future__ import annotations

import streamlit as st
from loguru import logger

from data.quality import DataSource
from ui.styles import (
    C_ACCENT,
    C_HIGH,
    C_LOW,
    C_MOD,
    C_TEXT,
    C_TEXT2,
    C_TEXT3,
    badge,
    live_data_badge,
    metric_card_row,
    page_header,
    section_header,
    wsj_market_table,
)


# ── Domain-specific color mappings ──────────────────────────────────────────
# Keep *semantic* mappings local to the tab; palette constants live in styles.

_TONE_COLOR: dict[str, str] = {
    "BULLISH": C_HIGH,
    "BEARISH": C_LOW,
    "NEUTRAL": C_MOD,
}


def _tone_color(tone: str) -> str:
    return _TONE_COLOR.get(tone, C_MOD)


def _change_color(pct: float | None) -> str:
    if pct is None:
        return C_TEXT2
    if pct > 0:
        return C_HIGH
    if pct < 0:
        return C_LOW
    return C_TEXT2


def _momentum_color(momentum: str) -> str:
    if not momentum:
        return C_TEXT2
    if "Rally" in momentum or "Uptrend" in momentum:
        return C_HIGH
    if "Decline" in momentum or "Downtrend" in momentum:
        return C_LOW
    return C_TEXT2


def _percentile_color(pct: float) -> str:
    if pct > 70:
        return C_HIGH
    if pct < 30:
        return C_LOW
    return C_TEXT2


# ── Cell formatters for WSJ market tables ───────────────────────────────────

def _mono(value: str, color: str = C_TEXT, weight: int = 600) -> str:
    return (
        f'<span style="font-family:var(--mono);color:{color};font-weight:{weight};'
        f'font-variant-numeric:tabular-nums;">{value}</span>'
    )


def _sans(value: str, color: str = C_TEXT2, weight: int = 500) -> str:
    return (
        f'<span style="font-family:var(--sans);color:{color};font-weight:{weight};">'
        f'{value}</span>'
    )


def _range_bar(low: float, high: float, pos: float) -> str:
    """Render a thin 52-week range bar with a dot at ``pos`` (percent)."""
    label = (
        f'<span style="display:flex;justify-content:space-between;margin-bottom:3px;'
        f'font-family:var(--mono);font-size:0.66rem;color:{C_TEXT3};">'
        f'<span>{low:,.0f}</span><span>{high:,.0f}</span></span>'
    )
    track = (
        f'<span style="display:block;height:4px;'
        f'background:rgba(232,230,225,0.06);border-radius:2px;position:relative;">'
        f'<span style="position:absolute;left:{pos:.0f}%;top:-2px;width:8px;height:8px;'
        f'border-radius:50%;background:{C_ACCENT};transform:translateX(-50%);"></span>'
        f'</span>'
    )
    return f'<span style="display:block;min-width:140px;">{label}{track}</span>'


# ── Data provenance sources ─────────────────────────────────────────────────
# Narrative content is *modeled* — it's generated deterministically from live
# freight/macro/stock feeds. See processing/market_commentary.py and the
# forthcoming engine/narration_engine.py.

def _narration_source(label: str, detail: str) -> DataSource:
    return DataSource.modeled(
        label,
        notes=(
            f"{detail} — generated by processing.market_commentary "
            "(future: engine/narration_engine.py)"
        ),
    )


# ── Section renderers ───────────────────────────────────────────────────────

def _render_header_and_lede(wrap: dict) -> None:
    """WSJ-style page header with tone badge and editorial lede."""
    tone = wrap.get("market_tone", "NEUTRAL")
    date_str = wrap.get("date", "")
    subtitle_bits = [s for s in (date_str, wrap.get("subhead", "")) if s]

    page_header(
        title=wrap.get("headline", "Daily Market Commentary"),
        subtitle=" · ".join(subtitle_bits),
        badge_text=tone,
        badge_color=_tone_color(tone),
    )

    st.html(
        live_data_badge(
            _narration_source(
                "Market Commentary Engine",
                "Auto-generated daily wrap from live freight and equity feeds",
            )
        )
    )

    body = wrap.get("body") or []
    if body:
        for p in body:
            st.markdown(p)


def _render_key_movers(movers: list[dict]) -> None:
    if not movers:
        return
    section_header("Key Movers", subtitle="Largest single-day moves across tracked shipping equities")
    st.html(
        live_data_badge(
            DataSource.modeled(
                "Equity Movers",
                notes="Computed from live stock feeds (last two closes)",
            )
        )
    )

    limited = movers[:5]
    metric_card_row(
        [
            {
                "label": m["ticker"],
                "value": f"${m['price']:.2f}",
                "accent": _change_color(m.get("change_pct")),
                "sublabel": (
                    f"{'+' if m.get('change_pct', 0) >= 0 else ''}"
                    f"{m.get('change_pct', 0):.1f}%"
                ),
            }
            for m in limited
        ],
        columns=len(limited),
    )


def _render_shipping_indices(indices: list[dict]) -> None:
    if not indices:
        return
    section_header(
        "Shipping Indices",
        subtitle="Key freight benchmarks with 52-week context and momentum regime",
    )
    st.html(
        live_data_badge(
            DataSource.modeled(
                "Index Tracker",
                notes="Baltic / Drewry / Freightos composite — from processing.index_tracker",
            )
        )
    )

    headers = ["Index", "Current", "1d Chg", "52w Range", "Pctile", "Momentum", "Commentary"]
    rows: list[list[str]] = []

    for idx in indices:
        current = idx.get("current")
        if current is None:
            continue

        chg_1d = idx.get("change_1d")
        chg_color = _change_color(chg_1d)
        if chg_1d is None:
            chg_str = "--"
        else:
            chg_str = f"{'+' if chg_1d >= 0 else ''}{chg_1d:.1f}%"

        pctile = idx.get("percentile", 50)
        range_pos = idx.get("range_position", 50)
        high_52 = idx.get("high_52w")
        low_52 = idx.get("low_52w")
        momentum = idx.get("momentum", "N/A")
        commentary = idx.get("commentary", "")
        source_name = idx.get("source", "")

        name_cell = (
            f'<span style="display:block;line-height:1.3;">'
            f'<span style="display:block;font-family:var(--serif);font-size:0.96rem;'
            f'font-weight:700;color:{C_TEXT};">{idx.get("name", "")}</span>'
            f'<span style="display:block;font-family:var(--sans);font-size:0.66rem;'
            f'color:{C_TEXT3};margin-top:2px;">{source_name}</span>'
            f'</span>'
        )

        range_cell = (
            _range_bar(low_52, high_52, range_pos)
            if (high_52 is not None and low_52 is not None)
            else _sans("--", color=C_TEXT3)
        )

        rows.append([
            name_cell,
            _mono(f"{current:,.0f}", color=C_TEXT, weight=700),
            _mono(chg_str, color=chg_color, weight=600),
            range_cell,
            _mono(f"{pctile:.0f}th", color=_percentile_color(pctile), weight=600),
            badge(momentum, color=_momentum_color(momentum)),
            _sans(commentary, color=C_TEXT2, weight=400),
        ])

    if rows:
        wsj_market_table(headers, rows)


def _render_forward_outlook(outlook: dict) -> None:
    section_header("Forward Outlook", subtitle="Opportunities and risks over the next 5–20 sessions")
    st.html(
        live_data_badge(
            _narration_source(
                "Forward Outlook Engine",
                "Ranked opportunity and risk signals from insight store",
            )
        )
    )

    narrative = outlook.get("narrative", "")
    if narrative:
        st.markdown(narrative)

    opportunities = outlook.get("opportunities", []) or []
    risks = outlook.get("risks", []) or []

    c1, c2 = st.columns(2)
    with c1:
        _render_signal_column(
            "Opportunities",
            opportunities,
            accent=C_HIGH,
            value_fn=lambda o: f"{o.get('score', 0):.0%} conviction",
            value_color=C_HIGH,
        )
    with c2:
        _render_signal_column(
            "Key Risks",
            risks,
            accent=C_LOW,
            value_fn=lambda r: str(r.get("category", "")).lower().replace("_", " ") or "risk",
            value_color=C_LOW,
        )


def _render_signal_column(
    heading: str,
    items: list[dict],
    *,
    accent: str,
    value_fn,
    value_color: str,
) -> None:
    """Render a titled column of signal rows (Opportunities / Risks)."""
    if not items:
        st.markdown(
            f'<div class="sub-section-header">{heading}</div>',
            unsafe_allow_html=True,
        )
        st.markdown("No items to report.")
        return

    st.markdown(
        f'<div class="sub-section-header">{heading}</div>',
        unsafe_allow_html=True,
    )

    rows_html = []
    for it in items:
        title = str(it.get("title", ""))[:80]
        meta = value_fn(it)
        rows_html.append(
            f'<div class="wsj-news-item">'
            f'<span style="display:block;font-family:var(--serif);font-size:0.84rem;'
            f'font-weight:700;color:var(--text);line-height:1.3;">{title}</span>'
            f'<span style="display:block;font-family:var(--mono);font-size:0.7rem;'
            f'color:{value_color};margin-top:3px;">{meta}</span>'
            f'</div>'
        )
    st.markdown(
        f'<div class="wsj-whats-news">{"".join(rows_html)}</div>',
        unsafe_allow_html=True,
    )


# ── Public entry point ──────────────────────────────────────────────────────

def render(
    stock_data=None,
    freight_data=None,
    macro_data=None,
    port_results=None,
    insights=None,
    **kwargs,
) -> None:
    """Render the daily market commentary dashboard."""
    try:
        from processing.index_tracker import compute_index_dashboard
        from processing.market_commentary import (
            generate_daily_wrap,
            generate_forward_outlook,
        )
    except ImportError as e:
        st.error(f"Commentary modules unavailable: {e}")
        return

    stock_data = stock_data or {}
    freight_data = freight_data or {}
    macro_data = macro_data or {}
    port_results = port_results or []
    insights = insights or []

    try:
        wrap = generate_daily_wrap(
            stock_data, freight_data, macro_data, port_results, insights
        )
        outlook = generate_forward_outlook(insights, macro_data, freight_data)
        indices = compute_index_dashboard(freight_data, macro_data)
    except Exception:
        logger.exception("Commentary generation failed")
        st.error("Daily Market Commentary could not be generated.")
        return

    try:
        _render_header_and_lede(wrap)
        _render_key_movers(wrap.get("key_movers", []) or [])
        _render_shipping_indices(indices or [])
        _render_forward_outlook(outlook or {})
    except Exception:
        logger.exception("tab_commentary top-level render failed")
        st.error("Daily Market Commentary encountered an error.")
